# Generated by Django 2.2.19 on 2023-01-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Оператор', 'Оператор'), ('Сотрудник офиса', 'Сотрудник офиса'), ('Руководитель', 'Руководитель'), ('Администратор', 'Администратор')], max_length=30, verbose_name='Права доступа'),
        ),
    ]
