# Generated by Django 2.2.19 on 2023-01-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='del_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='del_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='del_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
