# Generated by Django 2.2.19 on 2023-01-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0002_auto_20230107_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
    ]
