# Generated by Django 2.2.19 on 2023-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0002_auto_20230105_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, verbose_name='Год')),
                ('cemetery_name', models.CharField(blank=True, max_length=512, verbose_name='Наименование кладбища')),
                ('number', models.IntegerField(blank=True, verbose_name='Номер')),
                ('surname', models.CharField(blank=True, max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('age_deceased', models.DateField(blank=True, verbose_name='Возраст умершего')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('burial_date', models.DateField(blank=True, verbose_name='Дата захоронения')),
                ('area', models.CharField(blank=True, max_length=50, verbose_name='Участок')),
                ('grave', models.CharField(blank=True, max_length=50, verbose_name='Могила')),
                ('evidence', models.CharField(blank=True, max_length=50, verbose_name='№ свидетельства о смерти из ЗАГСа')),
                ('registry_office', models.CharField(blank=True, max_length=10, verbose_name='Каким ЗАГСом выдано свидетельство')),
                ('responsible_for_burial', models.TextField(blank=True, verbose_name='Ф.И.О. ответственного за захоронение и его адрес')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('sys_user', models.CharField(max_length=50)),
                ('sys_data', models.DateField(auto_now_add=True)),
                ('sys_del', models.BooleanField(default=False)),
                ('sys_del_user', models.CharField(blank=True, max_length=50)),
                ('sys_del_data', models.DateField(blank=True)),
            ],
        ),
    ]
