# Generated by Django 2.2.19 on 2023-01-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0003_auto_20230107_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='age_deceased',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст умершего'),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
